// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqkkadvttyxtalrlvqpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxa2thZHZ0dHl4dGFscmx2cXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODA5NjQsImV4cCI6MjA1OTQ1Njk2NH0.c1V1PkjNqcs2jGprwXYXLE-zQZhzejgD8y1W0i_0E7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);